### ISSUE TITLE
Privacy Pool V1.0 Release

### ISSUE THREAD

**Issue by FeurJak** [0xbow-io/privacy-pool-V1.0#19]
# Scope: 

This Release Plan targets Privacy Pool Launch on Gnosis. 

# FEATURES: 
- [ ] [FEAT-(ZK): Proof-Of-Association Circuit Implementation](https://github.com/0xbow-io/privacy-pool-V1.0/issues/9)
- [ ] [FEAT-(EXTERN): Relayer / Paymaster Integration](https://github.com/0xbow-io/privacy-pool-V1.0/issues/10)
- [ ] [FEAT-(UI): ASP Page](https://github.com/0xbow-io/privacy-pool-V1.0/issues/11)
- [ ] [FEAT-(UI): Record Page](https://github.com/0xbow-io/privacy-pool-V1.0/issues/12)

# ADHOC: 
- [ ] [ENHANCE-(UI): UI/UX Optimisations](https://github.com/0xbow-io/privacy-pool-V1.0/issues/13)

# QA: 
- [ ] [Circuit Audit](https://github.com/0xbow-io/privacy-pool-V1.0/issues/14)
- [ ] [Smart Contract Audit](https://github.com/0xbow-io/privacy-pool-V1.0/issues/15)
- [ ] [CICD](https://github.com/0xbow-io/privacy-pool-V1.0/issues/16)

# Test Plan: 
- TBD

# DOCS: 
- [ ] [DOCS-(ZK): Documentation & Specification for ZK Circuits](https://github.com/0xbow-io/privacy-pool-V1.0/issues/17)
- [ ] [DOCS-(CONTRACTS): Documentation & Specification for Contracts](https://github.com/0xbow-io/privacy-pool-V1.0/issues/18)

# BD / MARKETING:

**Comment by FeurJak** [comment]
@refisolarpunk could you fill out any BD / Marketing related tasks for the Privacy Pool V1.0 Release
